#!/bin/bash
if [ $# -eq 0 ]; then
	repo=$(gh repo view --json=nameWithOwner --jq ".nameWithOwner" | tee)
	echo "Using repo: $repo"
else
	repo=$1
fi

# from: https://stackoverflow.com/a/60766849/5693170
# modified to be used as a gh extension to avoid specifying tokens

# Using tee to disable pager
gh api repos/$repo/actions/runs \
    --paginate \
    --jq '.workflow_runs[] | select([.status] | inside(["queued"])) | .id' |
    xargs -t -I {} gh run cancel {}

